<?php 
/**
 * Taxonomies importer ( langauges )
 */





add_action('init',function(){
    $data = array(
        "Akka",
        "Angular",
        "ASP.NET",
        "Bash",
        "Bottle",
        "Boost",
        "CakePHP",
        "C++",
        "Cocoa Touch",
        "CodeIgniter",
        "Django",
        "Django CMS",
        "Drupal",
        "Entity Framework",
        "Express.js",
        "Flask",
        "Gin",
        "Go",
        "Grails",
        "Groovy",
        "Hibernate",
        "Hugo",
        "Java",
        "JavaScript",
        "Joomla",
        "Kotlin",
        "Ktor",
        "Laravel",
        "Lapis",
        "Lua",
        "Liferay",
        "Magnolia",
        "MATLAB",
        "Mojolicious",
        "Node.js",
        "Nest.js",
        "Next.js",
        "Objective-C",
        "OpenResty",
        "Perl",
        "PHP",
        "Play Framework",
        "Play Framework",
        "PowerShell",
        "Pyramid",
        "Python",
        "Qt",
        "React",
        "Refinery CMS",
        "Ruby",
        "Ruby on Rails",
        "Rust",
        "Scala",
        "Shell scripting",
        "Shiny",
        "Sinatra",
        "Sitecore",
        "Spring",
        "Spring Boot",
        "Struts",
        "Symfony",
        "Swift",
        "SwiftUI",
        "TypeScript",
        "Umbraco",
        "Vue.js",
        "Wagtail",
        "WordPress"
    );
    
    foreach($data as $term){
        wp_insert_term($term, 'languages');
    }
});




add_action('init',function(){
    $tools = array(
        'GitHub',
        'Basecamp',
        'Slack',
        'GitLab',
        'Docker',
        'Bitbucket',
        'Trello',
        'Jira',
        'Asana',
        'Jenkins',
        'CircleCI',
        'Travis CI',
        'Ansible',
        'Puppet',
        'Chef',
        'Kubernetes',
        'Vagrant',
        'Heroku',
        'AWS Elastic Beanstalk',
        'TeamCity',
        'Bamboo',
        'Microsoft Teams',
        'Mattermost',
        'Rocket.Chat',
        'Zoom',
        'Visual Studio Code (VS Code)',
        'Sublime Text',
        'Atom',
        'IntelliJ IDEA',
        'Eclipse',
        'NetBeans',
        'Notepad++',
        'Vim',
        'Buddy Works',
        'GitKraken',
        'SourceForge',
        'Phabricator',
        'CodeShip',
        'Beautiful Soup',
        'Scrapy',
        'Selenium',
        'Puppeteer',
        'Octoparse',
        'Google Cloud Platform (GCP)',
        'Microsoft Azure',
        'IBM Cloud',
        'DigitalOcean',
        'Heroku',
        'Oracle Cloud Infrastructure (OCI)',
        'Alibaba Cloud',
        'GitHub Actions',
        'GitLab CI/CD',
        'Jenkins X',
        'GoCD',
        'Drone',
        'Concourse',
        'Argo CD',
        'Spinnaker',
        'AWS CodePipeline',
        'Azure DevOps',
        'Semaphore',
        'Codefresh',
        'Wercker',
        'MySQL',
        'PostgreSQL',
        'MongoDB',
        'Redis',
        'SQLite',
        'Microsoft SQL Server',
        'Oracle Database',
        'Amazon RDS',
        'Google Cloud SQL',
        'Firebase Realtime Database'
    );
    
    
    foreach($tools as $term){
        wp_insert_term($term, 'tools');
    }
});